export const AUTH_SERVICE = 'AUTH_SERVICE';
export const PASSWORD_SERVICE = 'PASSWORD_SERVICE';
export const TOKEN_SERVICE = 'TOKEN_SERVICE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const REFRESH_TOKEN_REPOSITORY = 'REFRESH_TOKEN_REPOSITORY';
